/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cdi117
 */
public class AppUI02 extends javax.swing.JFrame {

    /**
     * Creates new form AppUI02
     */
    public AppUI02() {
        initComponents();
         JLnaissance.setVisible( false);
          JLmobile.setVisible( false);
           jTextFieldNaissance.setVisible( false);
            jTextFieldMobile.setVisible( false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jRadioConnaissance = new javax.swing.JRadioButton();
        jRadioButtonFamille = new javax.swing.JRadioButton();
        jRadioButtonAmi = new javax.swing.JRadioButton();
        jTextFieldNom = new javax.swing.JTextField();
        JLnom = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        JLprenom = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        JLadresse = new javax.swing.JLabel();
        jTextFieldCP = new javax.swing.JTextField();
        JLcp = new javax.swing.JLabel();
        jTextFieldVille = new javax.swing.JTextField();
        JLville = new javax.swing.JLabel();
        jTextFieldTelphone = new javax.swing.JTextField();
        JLtelephone = new javax.swing.JLabel();
        jTextFieldMobile = new javax.swing.JTextField();
        JLmobile = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        JLemail = new javax.swing.JLabel();
        jTextFieldNaissance = new javax.swing.JTextField();
        JLnaissance = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Creation de contact");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        buttonGroup1.add(jRadioConnaissance);
        jRadioConnaissance.setText("Connaissance");
        jRadioConnaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioConnaissanceActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioConnaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        buttonGroup1.add(jRadioButtonFamille);
        jRadioButtonFamille.setText("Famille");
        jRadioButtonFamille.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonFamilleItemStateChanged(evt);
            }
        });
        jRadioButtonFamille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFamilleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFamille, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        buttonGroup1.add(jRadioButtonAmi);
        jRadioButtonAmi.setText("Ami");
        jRadioButtonAmi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonAmiStateChanged(evt);
            }
        });
        jRadioButtonAmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAmiActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jTextFieldNom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNom.setText(" ");
        getContentPane().add(jTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 240, -1));

        JLnom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLnom.setText("Nom");
        getContentPane().add(JLnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 90, 120, -1));

        jTextFieldPrenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrenom.setText(" ");
        jTextFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 240, -1));

        JLprenom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLprenom.setText("Prenom");
        getContentPane().add(JLprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, -1));

        jTextFieldAdresse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAdresse.setText(" ");
        getContentPane().add(jTextFieldAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 240, -1));

        JLadresse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLadresse.setText("Adresse");
        getContentPane().add(JLadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, -1));

        jTextFieldCP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCP.setText(" ");
        getContentPane().add(jTextFieldCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 240, -1));

        JLcp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLcp.setText("CP");
        getContentPane().add(JLcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, -1));

        jTextFieldVille.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVille.setText(" ");
        getContentPane().add(jTextFieldVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 240, -1));

        JLville.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLville.setText("Ville");
        getContentPane().add(JLville, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, -1));

        jTextFieldTelphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTelphone.setText(" ");
        getContentPane().add(jTextFieldTelphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 240, -1));

        JLtelephone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLtelephone.setText("Telephone");
        getContentPane().add(JLtelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, -1));

        jTextFieldMobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMobile.setText(" ");
        getContentPane().add(jTextFieldMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 240, -1));

        JLmobile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLmobile.setText("Mobile");
        getContentPane().add(JLmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, -1));

        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail.setText(" ");
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 240, -1));

        JLemail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLemail.setText("Email");
        getContentPane().add(JLemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, -1));

        jTextFieldNaissance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNaissance.setText(" ");
        getContentPane().add(jTextFieldNaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 240, -1));

        JLnaissance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLnaissance.setText("Date de naissance");
        getContentPane().add(JLnaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, -1));

        jButtonSave.setText("Enregistrer");
        getContentPane().add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomActionPerformed

    private void jRadioButtonFamilleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonFamilleItemStateChanged
//jTextFieldMobile.setVisible( jRadioButtonFamille.isSelected());
//jTextFieldNaissance.setVisible( jRadioButtonFamille.isSelected());
//JLnaissance.setVisible( jRadioButtonFamille.isSelected());
//JLmobile.setVisible( jRadioButtonFamille.isSelected());
    }//GEN-LAST:event_jRadioButtonFamilleItemStateChanged

    private void jRadioButtonAmiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonAmiStateChanged
//       JLmobile.setVisible( jRadioButtonAmi.isSelected());
//       jTextFieldMobile.setVisible( jRadioButtonAmi.isSelected());
    }//GEN-LAST:event_jRadioButtonAmiStateChanged

    private void jRadioButtonAmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAmiActionPerformed
          jTextFieldMobile.setVisible( jRadioButtonAmi.isSelected());
jTextFieldNaissance.setVisible(false);
JLnaissance.setVisible( false);
JLmobile.setVisible( jRadioButtonAmi.isSelected());
    }//GEN-LAST:event_jRadioButtonAmiActionPerformed

    private void jRadioButtonFamilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFamilleActionPerformed
    jTextFieldMobile.setVisible( jRadioButtonFamille.isSelected());
jTextFieldNaissance.setVisible( jRadioButtonFamille.isSelected());
JLnaissance.setVisible( jRadioButtonFamille.isSelected());
JLmobile.setVisible( jRadioButtonFamille.isSelected());
    }//GEN-LAST:event_jRadioButtonFamilleActionPerformed

    private void jRadioConnaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioConnaissanceActionPerformed
       jTextFieldMobile.setVisible(false);
jTextFieldNaissance.setVisible(false);
JLnaissance.setVisible( false);
JLmobile.setVisible(false);
    }//GEN-LAST:event_jRadioConnaissanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppUI02().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLadresse;
    private javax.swing.JLabel JLcp;
    private javax.swing.JLabel JLemail;
    private javax.swing.JLabel JLmobile;
    private javax.swing.JLabel JLnaissance;
    private javax.swing.JLabel JLnom;
    private javax.swing.JLabel JLprenom;
    private javax.swing.JLabel JLtelephone;
    private javax.swing.JLabel JLville;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonAmi;
    private javax.swing.JRadioButton jRadioButtonFamille;
    private javax.swing.JRadioButton jRadioConnaissance;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMobile;
    private javax.swing.JTextField jTextFieldNaissance;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldTelphone;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables
}
