
import java.util.Enumeration;
import javax.swing.JRadioButton;

public class jf01 extends javax.swing.JFrame {

    public jf01() {
        initComponents();
        jCheckBox1.setSelected(true);
        jPanel1.setVisible( false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(null);

        jLabel1.setText("Nom :");
        jLabel1.setToolTipText("!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 360, 30);

        jTextField1.setToolTipText("Saisir le nom !");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 50, 360, 30);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 90, 360, 23);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 130, 360, 30);

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(10, 170, 130, 40);

        jCheckBox2.setText("jCheckBox2");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(10, 210, 110, 30);

        jCheckBox3.setText("jCheckBox3");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(10, 250, 110, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mon Titre", 0, 1), "Mon Titre"), "mon Titre"));
        jPanel1.setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Mr");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(220, 20, 140, 40);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Mme");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(220, 60, 140, 40);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Mlle");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(220, 100, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 300, 380, 170);

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(200, 180, 105, 23);

        setBounds(0, 0, 435, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jLabel2.setText( jTextField1.getText().toUpperCase());
        System.out.println("check box 1 :" + jCheckBox1.isSelected());
        System.out.println("check box 2 :" + jCheckBox2.isSelected());
        System.out.println("check box 3 :" + jCheckBox3.isSelected());
        
        System.out.println( "Mr :"+ jRadioButton1.isSelected());
        System.out.println( "Mme :"+ jRadioButton2.isSelected());
        System.out.println( "Mlle :"+ jRadioButton3.isSelected());
        System.out.println("---");
        for (   Enumeration e =buttonGroup1.getElements(); e.hasMoreElements(); ) {
            JRadioButton rb= (JRadioButton) e.nextElement();
            System.out.println( rb.getText()+":"+rb.isSelected());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible( jToggleButton1.isSelected());
        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        jPanel1.setVisible( jCheckBox1.isSelected());
        
        
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jf01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jf01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jf01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jf01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
